AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kagura

  Sample SAM Template for kagura

Globals:
  Function:
    Timeout: 5

Params:
  CONSUMER_SECRET:
    Type: String

Resources:
  TwitterGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitter/get/
      Handler: twitter-get
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /twitter_webhook
            Method: GET
      Environment:
        Variables:
          CONSUMER_SECRET: !Ref CONSUMER_SECRET
